import dayjs from 'dayjs'
import type { ClaimRequest } from '@/pages/general-info/claims-helpers'
import type { ClaimRequestFormValues } from './claim-request-form-helpers'

export interface AttachmentFile {
  id: string
  name: string
  url: string
}

// Mock prefilled detail of a submitted claim. In the real webview the host injects
// an existing claim record; here the values come from the design screenshots.
export const MOCK_CLAIM_DETAIL: ClaimRequestFormValues = {
  // Insured person
  driverCode: '6062006',
  fullName: 'Trần Việt Dũng',
  gender: 'Nam',
  idNumber: '',
  birthDate: '',
  email: '',
  zaloPhone: '',
  // Accident & medical
  accidentDate: dayjs('2026-06-01'),
  accidentPlace: '1 Le Duan',
  examDate: dayjs('2026-06-02'),
  admissionDate: dayjs('2026-06-03'),
  treatmentPlace: '',
  diagnosis: 'Testing',
  consequence: 'Testing',
  treatmentType: 'outpatient',
  treatmentFrom: undefined,
  treatmentTo: undefined,
  // Payment
  requestedAmount: 1000,
  paymentCases: ['medicalExpense', 'hospitalAllowance'],
  beneficiaryName: 'Tran Viet Dung',
  accountNumber: '0000000000',
  bankName: 'Testing',
  bankAddress: '',
  // Commitment fields are not rendered on the detail page; set true for type completeness.
  commitTruthful: true,
  commitThirdParty: true,
  commitSignature: true,
}

// Per-claim detail narrative keyed by the list row id (c1..c12). The shared
// fields (accidentDate, requestedAmount) are intentionally omitted here — they
// come from the list row in buildClaimDetail so the list stays the single
// source of truth and the two views never drift.
type ClaimDetailOverride = Partial<ClaimRequestFormValues>

export const CLAIM_DETAIL_OVERRIDES: Record<string, ClaimDetailOverride> = {
  c1: {
    accidentPlace: 'Số 1 Lê Duẩn, Quận 1, TP.HCM',
    examDate: dayjs('2026-06-02'),
    admissionDate: undefined,
    treatmentPlace: 'Phòng khám Đa khoa Quận 1',
    diagnosis: 'Chấn thương phần mềm vùng cẳng chân phải',
    consequence: 'Trầy xước, bầm tím, hạn chế vận động nhẹ',
    treatmentType: 'outpatient',
    treatmentFrom: undefined,
    treatmentTo: undefined,
    paymentCases: ['medicalExpense'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '0011001234567',
    bankName: 'Vietcombank',
    bankAddress: 'CN Hồ Chí Minh',
  },
  c2: {
    accidentPlace: 'Ngã tư Hàng Xanh, Bình Thạnh, TP.HCM',
    examDate: dayjs('2026-05-28'),
    admissionDate: dayjs('2026-05-28'),
    treatmentPlace: 'Bệnh viện Chợ Rẫy',
    diagnosis: 'Gãy kín 1/3 giữa xương đòn trái',
    consequence: 'Phải bó bột, nghỉ điều trị khoảng 4 tuần',
    treatmentType: 'inpatient',
    treatmentFrom: dayjs('2026-05-28'),
    treatmentTo: dayjs('2026-06-02'),
    paymentCases: ['medicalExpense', 'hospitalAllowance'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '21010001234567',
    bankName: 'BIDV',
    bankAddress: 'CN Sài Gòn',
  },
  c3: {
    accidentPlace: 'Đường Phạm Văn Đồng, TP. Thủ Đức',
    examDate: dayjs('2026-05-22'),
    admissionDate: undefined,
    treatmentPlace: 'Phòng khám tư nhân',
    diagnosis: 'Đau lưng sau va chạm giao thông',
    consequence: 'Không ghi nhận tổn thương thực thể rõ ràng',
    treatmentType: 'outpatient',
    treatmentFrom: undefined,
    treatmentTo: undefined,
    paymentCases: ['medicalExpense'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '19031234567890',
    bankName: 'Techcombank',
    bankAddress: 'CN Thủ Đức',
  },
  c4: {
    accidentPlace: 'Quốc lộ 1A, Huyện Bình Chánh, TP.HCM',
    examDate: dayjs('2026-05-15'),
    admissionDate: dayjs('2026-05-15'),
    treatmentPlace: 'Bệnh viện Nhân dân 115',
    diagnosis: 'Rách dây chằng khớp gối phải',
    consequence: 'Phẫu thuật nội soi, phục hồi chức năng',
    treatmentType: 'inpatient',
    treatmentFrom: dayjs('2026-05-15'),
    treatmentTo: dayjs('2026-05-19'),
    paymentCases: ['medicalExpense', 'hospitalAllowance'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '12345678901',
    bankName: 'ACB',
    bankAddress: 'CN Bình Chánh',
  },
  c5: {
    accidentPlace: 'Đường Nguyễn Văn Linh, Quận 7, TP.HCM',
    examDate: dayjs('2026-05-11'),
    admissionDate: undefined,
    treatmentPlace: 'Phòng khám Đa khoa Quận 7',
    diagnosis: 'Bong gân cổ chân trái',
    consequence: 'Sưng nề, đau khi đi lại',
    treatmentType: 'outpatient',
    treatmentFrom: undefined,
    treatmentTo: undefined,
    paymentCases: ['medicalExpense'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '0901234567',
    bankName: 'MB Bank',
    bankAddress: 'CN Quận 7',
  },
  c6: {
    accidentPlace: 'Vòng xoay Phú Lâm, Quận 6, TP.HCM',
    examDate: dayjs('2026-05-04'),
    admissionDate: undefined,
    treatmentPlace: 'Trung tâm Y tế Quận 6',
    diagnosis: 'Vết thương phần mềm bàn tay phải',
    consequence: 'Khâu 5 mũi, theo dõi nhiễm trùng',
    treatmentType: 'outpatient',
    treatmentFrom: undefined,
    treatmentTo: undefined,
    paymentCases: ['medicalExpense'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '180012345678',
    bankName: 'VPBank',
    bankAddress: 'CN Quận 6',
  },
  c7: {
    accidentPlace: 'Đường Trường Chinh, Quận Tân Bình, TP.HCM',
    examDate: dayjs('2026-05-02'),
    admissionDate: undefined,
    treatmentPlace: 'Phòng khám Đa khoa Tân Bình',
    diagnosis: 'Trầy xước nhẹ vùng khuỷu tay',
    consequence: 'Hồ sơ thiếu chứng từ y tế hợp lệ',
    treatmentType: 'outpatient',
    treatmentFrom: undefined,
    treatmentTo: undefined,
    paymentCases: ['medicalExpense'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '060012345678',
    bankName: 'Sacombank',
    bankAddress: 'CN Tân Bình',
  },
  c8: {
    accidentPlace: 'Cầu Sài Gòn, TP. Thủ Đức',
    examDate: dayjs('2026-04-24'),
    admissionDate: dayjs('2026-04-24'),
    treatmentPlace: 'Bệnh viện TP. Thủ Đức',
    diagnosis: 'Chấn thương cột sống thắt lưng',
    consequence: 'Điều trị bảo tồn, theo dõi vận động',
    treatmentType: 'inpatient',
    treatmentFrom: dayjs('2026-04-24'),
    treatmentTo: dayjs('2026-04-28'),
    paymentCases: ['medicalExpense', 'hospitalAllowance'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '10312345678',
    bankName: 'VietinBank',
    bankAddress: 'CN Thủ Đức',
  },
  c9: {
    accidentPlace: 'Đường Cách Mạng Tháng 8, Quận 3, TP.HCM',
    examDate: dayjs('2026-04-19'),
    admissionDate: undefined,
    treatmentPlace: 'Phòng khám Đa khoa Quận 3',
    diagnosis: 'Đụng dập vùng vai trái',
    consequence: 'Bầm tím, vận động khớp vai hạn chế',
    treatmentType: 'outpatient',
    treatmentFrom: undefined,
    treatmentTo: undefined,
    paymentCases: ['medicalExpense'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '0339123456',
    bankName: 'TPBank',
    bankAddress: 'CN Quận 3',
  },
  c10: {
    accidentPlace: 'Xa lộ Hà Nội, TP. Thủ Đức',
    examDate: dayjs('2026-04-12'),
    admissionDate: dayjs('2026-04-12'),
    treatmentPlace: 'Bệnh viện Đa khoa Thủ Đức',
    diagnosis: 'Vết thương vùng mặt',
    consequence: 'Khâu thẩm mỹ, theo dõi sẹo',
    treatmentType: 'inpatient',
    treatmentFrom: dayjs('2026-04-12'),
    treatmentTo: dayjs('2026-04-15'),
    paymentCases: ['medicalExpense', 'hospitalAllowance'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '040012345678',
    bankName: 'HDBank',
    bankAddress: 'CN Thủ Đức',
  },
  c11: {
    accidentPlace: 'Đường Võ Văn Kiệt, Quận 5, TP.HCM',
    examDate: dayjs('2026-04-06'),
    admissionDate: undefined,
    treatmentPlace: 'Phòng khám Đa khoa Quận 5',
    diagnosis: 'Bong gân khớp gối trái',
    consequence: 'Sưng đau, chườm lạnh và nghỉ ngơi',
    treatmentType: 'outpatient',
    treatmentFrom: undefined,
    treatmentTo: undefined,
    paymentCases: ['medicalExpense'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '0050123456789',
    bankName: 'OCB',
    bankAddress: 'CN Quận 5',
  },
  c12: {
    accidentPlace: 'Ngã sáu Gò Vấp, Quận Gò Vấp, TP.HCM',
    examDate: dayjs('2026-03-30'),
    admissionDate: dayjs('2026-03-30'),
    treatmentPlace: 'Bệnh viện Đa khoa Gò Vấp',
    diagnosis: 'Gãy xương cẳng tay phải',
    consequence: 'Bó bột, tái khám sau 4 tuần',
    treatmentType: 'inpatient',
    treatmentFrom: dayjs('2026-03-30'),
    treatmentTo: dayjs('2026-04-04'),
    paymentCases: ['medicalExpense', 'hospitalAllowance'],
    beneficiaryName: 'Trần Việt Dũng',
    accountNumber: '140012345678',
    bankName: 'Eximbank',
    bankAddress: 'CN Gò Vấp',
  },
}

// Build the detail shown for a clicked claim: the base template, overlaid with
// the per-claim narrative, with the shared fields always taken from the list row.
export function buildClaimDetail(claim: ClaimRequest | undefined): ClaimRequestFormValues {
  if (!claim) return MOCK_CLAIM_DETAIL
  return {
    ...MOCK_CLAIM_DETAIL,
    ...CLAIM_DETAIL_OVERRIDES[claim.id],
    accidentDate: dayjs(claim.accidentDate),
    requestedAmount: claim.requestedAmount,
  }
}

export const MOCK_ATTACHMENTS: AttachmentFile[] = [
  { id: '1', name: 'bien-ban-tai-nan.pdf', url: '#' },
  { id: '2', name: 'chung-tu-y-te.jpg', url: '#' },
  { id: '3', name: 'hoa-don-thanh-toan.pdf', url: '#' },
]
